apiVersion: v1
kind: PersistentVolume
metadata:
 name: mysql-pv
spec:
 capacity:
 storage: 2Gi # Adjust the storage capacity as needed
 accessModes:
 - ReadWriteOnce
 persistentVolumeReclaimPolicy: Delete # This means the volume will be deleted when the PVC is
deleted
 storageClassName: gp2 # Ensure this matches the storage class you intend to use
 hostPath: # For local testing, replace with AWS EBS or your cloud provider's specification
 path: /mnt/data/mysql # Adjust this path according to your environment
